//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotaFiscalNet.Core {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensagens {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagens() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MaxNFe.Mensagens", typeof(Mensagens).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EV0009|O valor informado para o CFOP não é válido..
        /// </summary>
        internal static string CFOPInvalido {
            get {
                return ResourceManager.GetString("CFOPInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EV0007|O valor informado para o CNAE Fiscal não é válido..
        /// </summary>
        internal static string CNAEInvalido {
            get {
                return ResourceManager.GetString("CNAEInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EV0005|O valor informado para o CNPJ não é válido..
        /// </summary>
        internal static string CNPJInvalido {
            get {
                return ResourceManager.GetString("CNPJInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EV0006|O valor informado para o CPF não é válido..
        /// </summary>
        internal static string CPFInvalido {
            get {
                return ResourceManager.GetString("CPFInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EV0001|O valor &apos;NaoEspecificado&apos; é inválido pois o campo {0} é obrigatório..
        /// </summary>
        internal static string EnumNaoEspecificado {
            get {
                return ResourceManager.GetString("EnumNaoEspecificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EV0002|O valor informado não é valido..
        /// </summary>
        internal static string GenericArgumentException {
            get {
                return ResourceManager.GetString("GenericArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ev0011|O código GTIN (Global Trade Item Number, antigo código EAN) informado não é válido..
        /// </summary>
        internal static string GTINInvalido {
            get {
                return ResourceManager.GetString("GTINInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EV0010|O valor informado para a Placa não é válido..
        /// </summary>
        internal static string PlacaInvalida {
            get {
                return ResourceManager.GetString("PlacaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EV0003|A Nota Fiscal Eletrônica não pode ser modificada por estar em modo somente-leitura..
        /// </summary>
        internal static string ReadOnlyClass {
            get {
                return ResourceManager.GetString("ReadOnlyClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EV0008|O valor informado para o Telefone não é válido..
        /// </summary>
        internal static string TelefoneInvalido {
            get {
                return ResourceManager.GetString("TelefoneInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EV0004|O valor informado é inválido.\r\nInforme um valor maior ou igual a &apos;{0}&apos; e menor ou igual a &apos;{1}&apos;..
        /// </summary>
        internal static string ValueOutOfRange {
            get {
                return ResourceManager.GetString("ValueOutOfRange", resourceCulture);
            }
        }
    }
}
